name: Greet New Contributor

on:
  pull_request:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Greet new contributor
        if: github.actor != 'your-username' # Avoid greeting yourself (use your GitHub username here)
        run: |
          # Checking if the user has made the first PR
          PR_AUTHOR=$(jq --raw-output .pull_request.user.login $GITHUB_EVENT_PATH)
          COMMENT="Hi @${PR_AUTHOR}, welcome to TrackHer! 🎉 Thanks for opening your first pull request. We're excited to have you contribute to our project! 😄"
          
          # Use GitHub's API to post a comment on the PR
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

